/**
 * Pins the Gradle JDK for the generated android/ project.
 *
 * React Native's Gradle setup targets JDK 17, but this machine's default JDKs
 * are newer. Android Studio ships a suitable JBR, so we point Gradle at it
 * rather than requiring another JVM install. android/ is git-ignored and
 * regenerated by `expo prebuild`, so this runs after every prebuild.
 *
 * No-ops (with a warning) when no JDK 17 is found, so the build fails with
 * Gradle's own message rather than a silently wrong toolchain.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const CANDIDATES = [
  process.env.FRAMECUE_GRADLE_JDK,
  'C:/Program Files/Android/Android Studio/jbr',
  'C:/Program Files/Eclipse Adoptium/jdk-17',
  '/usr/lib/jvm/java-17-openjdk',
].filter(Boolean);

const propertiesPath = join('android', 'gradle.properties');
if (!existsSync(propertiesPath)) {
  console.warn('[android-jdk] android/ not generated yet; skipping.');
  process.exit(0);
}

const jdk = CANDIDATES.find((candidate) => existsSync(join(candidate, 'bin')));
if (!jdk) {
  console.warn('[android-jdk] No JDK 17 found. Set FRAMECUE_GRADLE_JDK to one.');
  process.exit(0);
}

const KEY = 'org.gradle.java.home';
// Gradle properties want forward slashes, even on Windows.
const value = jdk.split(String.fromCharCode(92)).join('/');
const existing = readFileSync(propertiesPath, 'utf8');
const withoutKey = existing
  .split('\n')
  .filter((line) => !line.startsWith(`${KEY}=`))
  .join('\n')
  .replace(/\n+$/, '\n');

writeFileSync(propertiesPath, `${withoutKey}\n# Set by scripts/android-jdk.mjs\n${KEY}=${value}\n`);
console.log(`[android-jdk] ${KEY}=${value}`);
